# Generated by Django 5.1 on 2024-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('usuario', models.TextField(max_length=255)),
            ],
        ),
    ]
