# Generated by Django 5.1 on 2024-09-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cli', models.TextField(blank=True, max_length=255, null=True)),
                ('sobrenome', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('wpp', models.TextField(blank=True, max_length=255, null=True)),
                ('obs', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
