# Generated by Django 5.1 on 2024-09-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cli', models.TextField(blank=True, max_length=255, null=True)),
                ('sobrenome', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('wpp', models.TextField(blank=True, max_length=255, null=True)),
                ('obs', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('usuario', models.TextField(max_length=255)),
            ],
        ),
    ]
